version: '3'

services:
  alist-sync-web:
    build: .
    image: alist-sync:latest
    container_name: alist-sync
    restart: unless-stopped
    ports:
      - "52441:52441"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
